// Code generated by protoc-gen-go. DO NOT EDIT.
// source: truck_task_gen.proto

package wms_truck_task

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//主从库
type DB int32

const (
	//读库
	DB_READ DB = 0
	//写库
	DB_WRITE DB = 1
)

var DB_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}

var DB_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x DB) String() string {
	return proto.EnumName(DB_name, int32(x))
}

func (DB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{0}
}

type TruckTask struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskNo               string   `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	TmsTransId           string   `protobuf:"bytes,3,opt,name=tms_trans_id,json=tmsTransId,proto3" json:"tms_trans_id,omitempty"`
	TaskState            int32    `protobuf:"varint,4,opt,name=task_state,json=taskState,proto3" json:"task_state,omitempty"`
	TruckNo              string   `protobuf:"bytes,5,opt,name=truck_no,json=truckNo,proto3" json:"truck_no,omitempty"`
	TruckName            string   `protobuf:"bytes,6,opt,name=truck_name,json=truckName,proto3" json:"truck_name,omitempty"`
	TruckImage           string   `protobuf:"bytes,7,opt,name=truck_image,json=truckImage,proto3" json:"truck_image,omitempty"`
	DriverName           string   `protobuf:"bytes,8,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverMobile         string   `protobuf:"bytes,9,opt,name=driver_mobile,json=driverMobile,proto3" json:"driver_mobile,omitempty"`
	DriverName1          string   `protobuf:"bytes,10,opt,name=driver_name1,json=driverName1,proto3" json:"driver_name1,omitempty"`
	DriverMobile1        string   `protobuf:"bytes,11,opt,name=driver_mobile1,json=driverMobile1,proto3" json:"driver_mobile1,omitempty"`
	TaskOption           int32    `protobuf:"varint,12,opt,name=task_option,json=taskOption,proto3" json:"task_option,omitempty"`
	ExecTime             string   `protobuf:"bytes,13,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	TransPath            string   `protobuf:"bytes,14,opt,name=trans_path,json=transPath,proto3" json:"trans_path,omitempty"`
	StartRepositoryId    int32    `protobuf:"varint,15,opt,name=start_repository_id,json=startRepositoryId,proto3" json:"start_repository_id,omitempty"`
	ArriveRepositoryId   int32    `protobuf:"varint,16,opt,name=arrive_repository_id,json=arriveRepositoryId,proto3" json:"arrive_repository_id,omitempty"`
	Operator             string   `protobuf:"bytes,17,opt,name=operator,proto3" json:"operator,omitempty"`
	CreateTime           string   `protobuf:"bytes,18,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,19,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruckTask) Reset()         { *m = TruckTask{} }
func (m *TruckTask) String() string { return proto.CompactTextString(m) }
func (*TruckTask) ProtoMessage()    {}
func (*TruckTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{0}
}

func (m *TruckTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruckTask.Unmarshal(m, b)
}
func (m *TruckTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruckTask.Marshal(b, m, deterministic)
}
func (m *TruckTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruckTask.Merge(m, src)
}
func (m *TruckTask) XXX_Size() int {
	return xxx_messageInfo_TruckTask.Size(m)
}
func (m *TruckTask) XXX_DiscardUnknown() {
	xxx_messageInfo_TruckTask.DiscardUnknown(m)
}

var xxx_messageInfo_TruckTask proto.InternalMessageInfo

func (m *TruckTask) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TruckTask) GetTaskNo() string {
	if m != nil {
		return m.TaskNo
	}
	return ""
}

func (m *TruckTask) GetTmsTransId() string {
	if m != nil {
		return m.TmsTransId
	}
	return ""
}

func (m *TruckTask) GetTaskState() int32 {
	if m != nil {
		return m.TaskState
	}
	return 0
}

func (m *TruckTask) GetTruckNo() string {
	if m != nil {
		return m.TruckNo
	}
	return ""
}

func (m *TruckTask) GetTruckName() string {
	if m != nil {
		return m.TruckName
	}
	return ""
}

func (m *TruckTask) GetTruckImage() string {
	if m != nil {
		return m.TruckImage
	}
	return ""
}

func (m *TruckTask) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *TruckTask) GetDriverMobile() string {
	if m != nil {
		return m.DriverMobile
	}
	return ""
}

func (m *TruckTask) GetDriverName1() string {
	if m != nil {
		return m.DriverName1
	}
	return ""
}

func (m *TruckTask) GetDriverMobile1() string {
	if m != nil {
		return m.DriverMobile1
	}
	return ""
}

func (m *TruckTask) GetTaskOption() int32 {
	if m != nil {
		return m.TaskOption
	}
	return 0
}

func (m *TruckTask) GetExecTime() string {
	if m != nil {
		return m.ExecTime
	}
	return ""
}

func (m *TruckTask) GetTransPath() string {
	if m != nil {
		return m.TransPath
	}
	return ""
}

func (m *TruckTask) GetStartRepositoryId() int32 {
	if m != nil {
		return m.StartRepositoryId
	}
	return 0
}

func (m *TruckTask) GetArriveRepositoryId() int32 {
	if m != nil {
		return m.ArriveRepositoryId
	}
	return 0
}

func (m *TruckTask) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *TruckTask) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *TruckTask) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 按条件更新数据
type UpdateAndCondition struct {
	// 更新数据，如果filed对应为空值，则需要在 update_empty_fields 中声明
	Entity *TruckTask `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	//查询条件
	Query *Query `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 需要赋空值的字段
	UpdateEmptyFields    []string `protobuf:"bytes,3,rep,name=update_empty_fields,json=updateEmptyFields,proto3" json:"update_empty_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAndCondition) Reset()         { *m = UpdateAndCondition{} }
func (m *UpdateAndCondition) String() string { return proto.CompactTextString(m) }
func (*UpdateAndCondition) ProtoMessage()    {}
func (*UpdateAndCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{2}
}

func (m *UpdateAndCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAndCondition.Unmarshal(m, b)
}
func (m *UpdateAndCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAndCondition.Marshal(b, m, deterministic)
}
func (m *UpdateAndCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAndCondition.Merge(m, src)
}
func (m *UpdateAndCondition) XXX_Size() int {
	return xxx_messageInfo_UpdateAndCondition.Size(m)
}
func (m *UpdateAndCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAndCondition.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAndCondition proto.InternalMessageInfo

func (m *UpdateAndCondition) GetEntity() *TruckTask {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *UpdateAndCondition) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *UpdateAndCondition) GetUpdateEmptyFields() []string {
	if m != nil {
		return m.UpdateEmptyFields
	}
	return nil
}

//按条件查询
type Query struct {
	// 按照实体查询 （和sql查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 中声明
	EntityQuery *TruckTask `protobuf:"bytes,1,opt,name=entity_query,json=entityQuery,proto3" json:"entity_query,omitempty"`
	// 按照sql查询（和实体查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 中声明
	// "id=1 and status in(3,4) and createtime >'2018' "
	SqlQuery string `protobuf:"bytes,2,opt,name=sql_query,json=sqlQuery,proto3" json:"sql_query,omitempty"`
	// 用空值当检索条件的字段
	QueryEmptyFields []string `protobuf:"bytes,3,rep,name=query_empty_fields,json=queryEmptyFields,proto3" json:"query_empty_fields,omitempty"`
	//排序条件 ["id":"desc","create_time":asc"]
	OrderBy map[string]string `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//是否查询主库，默认不读取 DB.READ
	Db                   DB       `protobuf:"varint,5,opt,name=db,proto3,enum=wms_truck_task.DB" json:"db,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{3}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetEntityQuery() *TruckTask {
	if m != nil {
		return m.EntityQuery
	}
	return nil
}

func (m *Query) GetSqlQuery() string {
	if m != nil {
		return m.SqlQuery
	}
	return ""
}

func (m *Query) GetQueryEmptyFields() []string {
	if m != nil {
		return m.QueryEmptyFields
	}
	return nil
}

func (m *Query) GetOrderBy() map[string]string {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *Query) GetDb() DB {
	if m != nil {
		return m.Db
	}
	return DB_READ
}

//分页查询
type PageQuery struct {
	//查询条件
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{4}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *PageQuery) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageQuery) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type EntityResult struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *TruckTask `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EntityResult) Reset()         { *m = EntityResult{} }
func (m *EntityResult) String() string { return proto.CompactTextString(m) }
func (*EntityResult) ProtoMessage()    {}
func (*EntityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{5}
}

func (m *EntityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityResult.Unmarshal(m, b)
}
func (m *EntityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityResult.Marshal(b, m, deterministic)
}
func (m *EntityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityResult.Merge(m, src)
}
func (m *EntityResult) XXX_Size() int {
	return xxx_messageInfo_EntityResult.Size(m)
}
func (m *EntityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityResult.DiscardUnknown(m)
}

var xxx_messageInfo_EntityResult proto.InternalMessageInfo

func (m *EntityResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EntityResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EntityResult) GetData() *TruckTask {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResult struct {
	Code                 int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*TruckTask `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListResult) Reset()         { *m = ListResult{} }
func (m *ListResult) String() string { return proto.CompactTextString(m) }
func (*ListResult) ProtoMessage()    {}
func (*ListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{6}
}

func (m *ListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResult.Unmarshal(m, b)
}
func (m *ListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResult.Marshal(b, m, deterministic)
}
func (m *ListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResult.Merge(m, src)
}
func (m *ListResult) XXX_Size() int {
	return xxx_messageInfo_ListResult.Size(m)
}
func (m *ListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListResult proto.InternalMessageInfo

func (m *ListResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResult) GetData() []*TruckTask {
	if m != nil {
		return m.Data
	}
	return nil
}

type PageResult struct {
	Code                 int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *TruckTaskPageData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PageResult) Reset()         { *m = PageResult{} }
func (m *PageResult) String() string { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()    {}
func (*PageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{7}
}

func (m *PageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResult.Unmarshal(m, b)
}
func (m *PageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResult.Marshal(b, m, deterministic)
}
func (m *PageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResult.Merge(m, src)
}
func (m *PageResult) XXX_Size() int {
	return xxx_messageInfo_PageResult.Size(m)
}
func (m *PageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResult.DiscardUnknown(m)
}

var xxx_messageInfo_PageResult proto.InternalMessageInfo

func (m *PageResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PageResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PageResult) GetData() *TruckTaskPageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TruckTaskPageData struct {
	CurrentPage          int32        `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Count                int32        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*TruckTask `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TruckTaskPageData) Reset()         { *m = TruckTaskPageData{} }
func (m *TruckTaskPageData) String() string { return proto.CompactTextString(m) }
func (*TruckTaskPageData) ProtoMessage()    {}
func (*TruckTaskPageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9c1869830836da2, []int{8}
}

func (m *TruckTaskPageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruckTaskPageData.Unmarshal(m, b)
}
func (m *TruckTaskPageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruckTaskPageData.Marshal(b, m, deterministic)
}
func (m *TruckTaskPageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruckTaskPageData.Merge(m, src)
}
func (m *TruckTaskPageData) XXX_Size() int {
	return xxx_messageInfo_TruckTaskPageData.Size(m)
}
func (m *TruckTaskPageData) XXX_DiscardUnknown() {
	xxx_messageInfo_TruckTaskPageData.DiscardUnknown(m)
}

var xxx_messageInfo_TruckTaskPageData proto.InternalMessageInfo

func (m *TruckTaskPageData) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *TruckTaskPageData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TruckTaskPageData) GetList() []*TruckTask {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("wms_truck_task.DB", DB_name, DB_value)
	proto.RegisterType((*TruckTask)(nil), "wms_truck_task.TruckTask")
	proto.RegisterType((*Result)(nil), "wms_truck_task.Result")
	proto.RegisterType((*UpdateAndCondition)(nil), "wms_truck_task.UpdateAndCondition")
	proto.RegisterType((*Query)(nil), "wms_truck_task.Query")
	proto.RegisterMapType((map[string]string)(nil), "wms_truck_task.Query.OrderByEntry")
	proto.RegisterType((*PageQuery)(nil), "wms_truck_task.PageQuery")
	proto.RegisterType((*EntityResult)(nil), "wms_truck_task.EntityResult")
	proto.RegisterType((*ListResult)(nil), "wms_truck_task.ListResult")
	proto.RegisterType((*PageResult)(nil), "wms_truck_task.PageResult")
	proto.RegisterType((*TruckTaskPageData)(nil), "wms_truck_task.TruckTaskPageData")
}

func init() { proto.RegisterFile("truck_task_gen.proto", fileDescriptor_e9c1869830836da2) }

var fileDescriptor_e9c1869830836da2 = []byte{
	// 922 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0x6e, 0xee, 0xf1, 0x71, 0x9a, 0x26, 0xb3, 0x05, 0xdc, 0x2c, 0x68, 0xb3, 0x46, 0x48, 0x15,
	0x97, 0x88, 0x04, 0x21, 0xa1, 0x15, 0x3c, 0x6c, 0x9a, 0xb0, 0xaa, 0xb4, 0xb4, 0x8b, 0x37, 0x88,
	0x47, 0x6b, 0x12, 0x0f, 0x59, 0xab, 0xb1, 0x27, 0x1d, 0x8f, 0x0b, 0x11, 0x7f, 0x85, 0x47, 0xde,
	0xf9, 0x85, 0x48, 0xe8, 0x9c, 0xf1, 0x26, 0x6e, 0xd2, 0xb0, 0xed, 0x3e, 0x75, 0xe6, 0x7c, 0xdf,
	0xf9, 0xce, 0xd5, 0xd3, 0xc0, 0xb1, 0x56, 0xe9, 0xec, 0xca, 0xd7, 0x3c, 0xb9, 0xf2, 0xe7, 0x22,
	0xee, 0x2d, 0x95, 0xd4, 0x92, 0x35, 0x7f, 0x8f, 0x12, 0x7f, 0x83, 0xb8, 0xff, 0x96, 0xc1, 0x9a,
	0xe0, 0x75, 0xc2, 0x93, 0x2b, 0xd6, 0x84, 0x62, 0x18, 0x38, 0x85, 0x6e, 0xe1, 0xb4, 0xe2, 0x15,
	0xc3, 0x80, 0x7d, 0x04, 0x35, 0xf2, 0x8f, 0xa5, 0x53, 0xec, 0x16, 0x4e, 0x2d, 0xaf, 0x8a, 0xd7,
	0x0b, 0xc9, 0xba, 0xd0, 0xd0, 0x24, 0xc4, 0xe3, 0xc4, 0x0f, 0x03, 0xa7, 0x44, 0x28, 0xe8, 0x28,
	0x99, 0xa0, 0xe9, 0x3c, 0x60, 0x9f, 0x00, 0x90, 0x6b, 0xa2, 0xb9, 0x16, 0x4e, 0x99, 0x24, 0x2d,
	0xb4, 0xbc, 0x46, 0x03, 0x3b, 0x81, 0xba, 0xc9, 0x22, 0x96, 0x4e, 0x85, 0x9c, 0x6b, 0x74, 0xbf,
	0x90, 0xe4, 0x69, 0x20, 0x1e, 0x09, 0xa7, 0x4a, 0xa0, 0x65, 0x40, 0x1e, 0x09, 0xf6, 0x04, 0x6c,
	0x03, 0x87, 0x11, 0x9f, 0x0b, 0xa7, 0x96, 0x45, 0x46, 0xd3, 0x39, 0x5a, 0x90, 0x10, 0xa8, 0xf0,
	0x46, 0x28, 0x23, 0x50, 0x37, 0x04, 0x63, 0x22, 0x85, 0x4f, 0xe1, 0x30, 0x23, 0x44, 0x72, 0x1a,
	0x2e, 0x84, 0x63, 0x11, 0xa5, 0x61, 0x8c, 0x3f, 0x91, 0x8d, 0x3d, 0x85, 0x46, 0x4e, 0xa5, 0xef,
	0x00, 0x71, 0xec, 0x8d, 0x4c, 0x9f, 0x7d, 0x06, 0xcd, 0x5b, 0x3a, 0x7d, 0xc7, 0x26, 0xd2, 0x61,
	0x5e, 0xa8, 0x4f, 0x09, 0x63, 0x27, 0xe4, 0x52, 0x87, 0x32, 0x76, 0x1a, 0xd4, 0x0a, 0x6a, 0xce,
	0x25, 0x59, 0xd8, 0x63, 0xb0, 0xc4, 0x1f, 0x62, 0xe6, 0xeb, 0x30, 0x12, 0xce, 0x21, 0x49, 0xd4,
	0xd1, 0x30, 0x09, 0x23, 0x61, 0xba, 0x81, 0x5d, 0x5e, 0x72, 0xfd, 0xc6, 0x69, 0xbe, 0xed, 0x06,
	0x8f, 0x93, 0x57, 0x5c, 0xbf, 0x61, 0x3d, 0x78, 0x94, 0x68, 0xae, 0xb4, 0xaf, 0xc4, 0x52, 0x26,
	0xa1, 0x96, 0x6a, 0x85, 0xf3, 0x38, 0xa2, 0x20, 0x6d, 0x82, 0xbc, 0x35, 0x72, 0x1e, 0xb0, 0xaf,
	0xe1, 0x98, 0x2b, 0x4c, 0x6f, 0xcb, 0xa1, 0x45, 0x0e, 0xcc, 0x60, 0xb7, 0x3c, 0x3a, 0x50, 0x97,
	0x4b, 0xa1, 0xb8, 0x96, 0xca, 0x69, 0x9b, 0xe4, 0xde, 0xde, 0xb1, 0xb4, 0x99, 0x12, 0x5c, 0x0b,
	0x93, 0x3b, 0x33, 0xad, 0x36, 0x26, 0xca, 0xfe, 0x09, 0xd8, 0xe9, 0x32, 0x58, 0x13, 0x1e, 0x19,
	0x82, 0x31, 0x21, 0xc1, 0x1d, 0x42, 0xd5, 0x13, 0x49, 0xba, 0xd0, 0x8c, 0x41, 0x79, 0x26, 0x03,
	0x91, 0x6d, 0x1f, 0x9d, 0x59, 0x0b, 0x4a, 0x51, 0x32, 0xcf, 0x76, 0x0f, 0x8f, 0xc8, 0x0a, 0xb8,
	0xe6, 0xd9, 0xc2, 0xd1, 0xd9, 0xfd, 0xbb, 0x00, 0xec, 0x17, 0x92, 0x7c, 0x1e, 0x07, 0x67, 0x32,
	0x0e, 0x42, 0x6a, 0x6b, 0x1f, 0xaa, 0x22, 0xd6, 0xa1, 0x5e, 0x91, 0xa4, 0x3d, 0x38, 0xe9, 0xdd,
	0xde, 0xfd, 0xde, 0x7a, 0xef, 0xbd, 0x8c, 0xc8, 0xbe, 0x80, 0xca, 0x75, 0x2a, 0xd4, 0x8a, 0x22,
	0xda, 0x83, 0x0f, 0xb6, 0x3d, 0x7e, 0x46, 0xd0, 0x33, 0x1c, 0x6c, 0x7d, 0x56, 0x9b, 0x88, 0x96,
	0x7a, 0xe5, 0xff, 0x16, 0x8a, 0x45, 0x90, 0x38, 0xa5, 0x6e, 0xe9, 0xd4, 0xf2, 0xda, 0x06, 0x1a,
	0x23, 0xf2, 0x23, 0x01, 0xee, 0x3f, 0x45, 0xa8, 0x90, 0x00, 0xfb, 0x1e, 0x1a, 0x26, 0xa0, 0x6f,
	0xa2, 0xbd, 0x33, 0x3f, 0xdb, 0xd0, 0x8d, 0xf7, 0x63, 0xb0, 0x92, 0xeb, 0x85, 0xbf, 0x49, 0xd4,
	0xf2, 0xea, 0xc9, 0xf5, 0xc2, 0x80, 0x5f, 0x02, 0x23, 0xe0, 0xae, 0x9c, 0x5a, 0x84, 0xe4, 0x52,
	0x62, 0x3f, 0x40, 0x5d, 0xaa, 0x40, 0x28, 0x7f, 0xba, 0x72, 0xca, 0xdd, 0xd2, 0xa9, 0x3d, 0x70,
	0xef, 0x2c, 0xb9, 0x77, 0x89, 0xac, 0xe1, 0x6a, 0x1c, 0x6b, 0xb5, 0xf2, 0x6a, 0xd2, 0xdc, 0x98,
	0x0b, 0xc5, 0x60, 0x4a, 0x9f, 0x6f, 0x73, 0xc0, 0xb6, 0x1d, 0x47, 0x43, 0xaf, 0x18, 0x4c, 0x3b,
	0xcf, 0xa0, 0x91, 0x77, 0xc6, 0x91, 0x5e, 0x09, 0x53, 0xb2, 0xe5, 0xe1, 0x91, 0x1d, 0x43, 0xe5,
	0x86, 0x2f, 0x52, 0x91, 0xd5, 0x62, 0x2e, 0xcf, 0x8a, 0xdf, 0x15, 0xdc, 0x39, 0x58, 0xaf, 0xf8,
	0x5c, 0x98, 0xca, 0xd6, 0xb3, 0x29, 0xdc, 0x63, 0x36, 0x0c, 0xca, 0x4b, 0x7c, 0x1d, 0x8a, 0x66,
	0x99, 0xf0, 0x8c, 0x4f, 0x0e, 0xfe, 0xf5, 0xe3, 0x34, 0xa2, 0xf5, 0xa9, 0x78, 0x35, 0xbc, 0x5f,
	0xa4, 0x91, 0x3b, 0x83, 0xc6, 0x98, 0x3a, 0xfc, 0xa0, 0x5d, 0xfc, 0x2a, 0xb7, 0x8b, 0xff, 0x3b,
	0x3e, 0xb3, 0xa6, 0x1c, 0xe0, 0x65, 0x98, 0xe8, 0xf7, 0x0c, 0x51, 0xba, 0x4f, 0x88, 0x10, 0x00,
	0x1b, 0xf6, 0xa0, 0x10, 0xdf, 0xde, 0xaa, 0xe2, 0xe9, 0xde, 0x10, 0x28, 0x3c, 0xe2, 0x9a, 0x67,
	0xa1, 0xfe, 0x84, 0xf6, 0x0e, 0x84, 0x8f, 0xe6, 0x2c, 0x55, 0x4a, 0xc4, 0xda, 0xa7, 0xf6, 0x9b,
	0xc8, 0x76, 0x66, 0x43, 0x1a, 0x4e, 0x7b, 0x26, 0xd3, 0x58, 0x67, 0xa3, 0x31, 0x17, 0xac, 0x73,
	0x11, 0x26, 0xfa, 0x1e, 0x75, 0x22, 0xed, 0xf3, 0x13, 0x28, 0x8e, 0x86, 0xac, 0x0e, 0x65, 0x6f,
	0xfc, 0x7c, 0xd4, 0x3a, 0x60, 0x16, 0x54, 0x7e, 0xf5, 0xce, 0x27, 0xe3, 0x56, 0x61, 0xf0, 0x57,
	0x19, 0x5a, 0x6b, 0xfa, 0x6b, 0xa1, 0x6e, 0xc2, 0x99, 0x60, 0x2f, 0xe1, 0xe8, 0xcc, 0x3c, 0x4a,
	0xeb, 0x7f, 0x75, 0xfb, 0x63, 0x74, 0x3e, 0xde, 0x86, 0xf2, 0xbb, 0xe1, 0x1e, 0xb0, 0x4b, 0x38,
	0x32, 0xcf, 0xcd, 0x46, 0x6d, 0xe7, 0xb3, 0xd9, 0x7d, 0x8f, 0x3a, 0x1f, 0x6e, 0x73, 0xd6, 0x82,
	0x63, 0x68, 0xbc, 0x10, 0x7a, 0xa3, 0x76, 0xf7, 0x6e, 0xbf, 0x33, 0xaf, 0x17, 0xd0, 0xca, 0xcb,
	0xe0, 0xb2, 0xed, 0x93, 0xea, 0x6c, 0x9b, 0x37, 0x9b, 0xe9, 0x1e, 0xb0, 0x21, 0x1c, 0x8d, 0xc4,
	0x42, 0xe4, 0x0b, 0xdc, 0xa3, 0xb3, 0xbf, 0xa6, 0x4b, 0x38, 0xce, 0x27, 0x83, 0xb3, 0xa7, 0x84,
	0x76, 0xfa, 0xbe, 0xfe, 0xc2, 0x77, 0x93, 0xda, 0xec, 0xb2, 0x7b, 0xc0, 0x46, 0xd0, 0xce, 0x0b,
	0x9e, 0xd1, 0xde, 0x3c, 0x34, 0xad, 0x69, 0x95, 0x7e, 0x06, 0x7d, 0xf3, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x5e, 0xf1, 0xb3, 0x1e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TruckTaskServiceClient is the client API for TruckTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TruckTaskServiceClient interface {
	//创建
	CreateTruckTask(ctx context.Context, in *TruckTask, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明，如果要更新的是默认值 请使用update_empty_fields
	UpdateTruckTask(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTask(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTaskList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	DeleteTruckTask(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTaskPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTaskCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
}

type truckTaskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTruckTaskServiceClient(cc *grpc.ClientConn) TruckTaskServiceClient {
	return &truckTaskServiceClient{cc}
}

func (c *truckTaskServiceClient) CreateTruckTask(ctx context.Context, in *TruckTask, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/CreateTruckTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckTaskServiceClient) UpdateTruckTask(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/UpdateTruckTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckTaskServiceClient) GetTruckTask(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/GetTruckTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckTaskServiceClient) GetTruckTaskList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error) {
	out := new(ListResult)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/GetTruckTaskList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckTaskServiceClient) DeleteTruckTask(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/DeleteTruckTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckTaskServiceClient) GetTruckTaskPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error) {
	out := new(PageResult)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/GetTruckTaskPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckTaskServiceClient) GetTruckTaskCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wms_truck_task.TruckTaskService/GetTruckTaskCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TruckTaskServiceServer is the server API for TruckTaskService service.
type TruckTaskServiceServer interface {
	//创建
	CreateTruckTask(context.Context, *TruckTask) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明，如果要更新的是默认值 请使用update_empty_fields
	UpdateTruckTask(context.Context, *UpdateAndCondition) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTask(context.Context, *Query) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTaskList(context.Context, *Query) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	DeleteTruckTask(context.Context, *Query) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTaskPageList(context.Context, *PageQuery) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetTruckTaskCount(context.Context, *Query) (*Result, error)
}

// UnimplementedTruckTaskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTruckTaskServiceServer struct {
}

func (*UnimplementedTruckTaskServiceServer) CreateTruckTask(ctx context.Context, req *TruckTask) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTruckTask not implemented")
}
func (*UnimplementedTruckTaskServiceServer) UpdateTruckTask(ctx context.Context, req *UpdateAndCondition) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTruckTask not implemented")
}
func (*UnimplementedTruckTaskServiceServer) GetTruckTask(ctx context.Context, req *Query) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTruckTask not implemented")
}
func (*UnimplementedTruckTaskServiceServer) GetTruckTaskList(ctx context.Context, req *Query) (*ListResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTruckTaskList not implemented")
}
func (*UnimplementedTruckTaskServiceServer) DeleteTruckTask(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTruckTask not implemented")
}
func (*UnimplementedTruckTaskServiceServer) GetTruckTaskPageList(ctx context.Context, req *PageQuery) (*PageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTruckTaskPageList not implemented")
}
func (*UnimplementedTruckTaskServiceServer) GetTruckTaskCount(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTruckTaskCount not implemented")
}

func RegisterTruckTaskServiceServer(s *grpc.Server, srv TruckTaskServiceServer) {
	s.RegisterService(&_TruckTaskService_serviceDesc, srv)
}

func _TruckTaskService_CreateTruckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruckTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).CreateTruckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/CreateTruckTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).CreateTruckTask(ctx, req.(*TruckTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckTaskService_UpdateTruckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCondition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).UpdateTruckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/UpdateTruckTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).UpdateTruckTask(ctx, req.(*UpdateAndCondition))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckTaskService_GetTruckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).GetTruckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/GetTruckTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).GetTruckTask(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckTaskService_GetTruckTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).GetTruckTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/GetTruckTaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).GetTruckTaskList(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckTaskService_DeleteTruckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).DeleteTruckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/DeleteTruckTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).DeleteTruckTask(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckTaskService_GetTruckTaskPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).GetTruckTaskPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/GetTruckTaskPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).GetTruckTaskPageList(ctx, req.(*PageQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckTaskService_GetTruckTaskCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckTaskServiceServer).GetTruckTaskCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_truck_task.TruckTaskService/GetTruckTaskCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckTaskServiceServer).GetTruckTaskCount(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _TruckTaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wms_truck_task.TruckTaskService",
	HandlerType: (*TruckTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTruckTask",
			Handler:    _TruckTaskService_CreateTruckTask_Handler,
		},
		{
			MethodName: "UpdateTruckTask",
			Handler:    _TruckTaskService_UpdateTruckTask_Handler,
		},
		{
			MethodName: "GetTruckTask",
			Handler:    _TruckTaskService_GetTruckTask_Handler,
		},
		{
			MethodName: "GetTruckTaskList",
			Handler:    _TruckTaskService_GetTruckTaskList_Handler,
		},
		{
			MethodName: "DeleteTruckTask",
			Handler:    _TruckTaskService_DeleteTruckTask_Handler,
		},
		{
			MethodName: "GetTruckTaskPageList",
			Handler:    _TruckTaskService_GetTruckTaskPageList_Handler,
		},
		{
			MethodName: "GetTruckTaskCount",
			Handler:    _TruckTaskService_GetTruckTaskCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "truck_task_gen.proto",
}
