// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository_gen.proto

package wms_repository

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//主从库
type DB int32

const (
	//读库
	DB_READ DB = 0
	//写库
	DB_WRITE DB = 1
)

var DB_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}

var DB_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x DB) String() string {
	return proto.EnumName(DB_name, int32(x))
}

func (DB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{0}
}

type Repository struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProvinceId           int32    `protobuf:"varint,3,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	CityId               int32    `protobuf:"varint,4,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Longitude            string   `protobuf:"bytes,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             string   `protobuf:"bytes,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	RepositoryType       int32    `protobuf:"varint,8,opt,name=repository_type,json=repositoryType,proto3" json:"repository_type,omitempty"`
	Status               int32    `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Mastername           string   `protobuf:"bytes,10,opt,name=mastername,proto3" json:"mastername,omitempty"`
	UpdateTime           string   `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreateTime           string   `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Realname             string   `protobuf:"bytes,13,opt,name=realname,proto3" json:"realname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetProvinceId() int32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *Repository) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *Repository) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Repository) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Repository) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Repository) GetRepositoryType() int32 {
	if m != nil {
		return m.RepositoryType
	}
	return 0
}

func (m *Repository) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Repository) GetMastername() string {
	if m != nil {
		return m.Mastername
	}
	return ""
}

func (m *Repository) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Repository) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 按条件更新数据
type UpdateAndCondition struct {
	// 更新数据，如果filed对应为空值，则需要在 update_empty_fields 中声明
	Entity *Repository `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	//查询条件
	Query *Query `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 需要赋空值的字段
	UpdateEmptyFields    []string `protobuf:"bytes,3,rep,name=update_empty_fields,json=updateEmptyFields,proto3" json:"update_empty_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAndCondition) Reset()         { *m = UpdateAndCondition{} }
func (m *UpdateAndCondition) String() string { return proto.CompactTextString(m) }
func (*UpdateAndCondition) ProtoMessage()    {}
func (*UpdateAndCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{2}
}

func (m *UpdateAndCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAndCondition.Unmarshal(m, b)
}
func (m *UpdateAndCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAndCondition.Marshal(b, m, deterministic)
}
func (m *UpdateAndCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAndCondition.Merge(m, src)
}
func (m *UpdateAndCondition) XXX_Size() int {
	return xxx_messageInfo_UpdateAndCondition.Size(m)
}
func (m *UpdateAndCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAndCondition.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAndCondition proto.InternalMessageInfo

func (m *UpdateAndCondition) GetEntity() *Repository {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *UpdateAndCondition) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *UpdateAndCondition) GetUpdateEmptyFields() []string {
	if m != nil {
		return m.UpdateEmptyFields
	}
	return nil
}

//按条件查询
type Query struct {
	// 按照实体查询 （和sql查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 中声明
	EntityQuery *Repository `protobuf:"bytes,1,opt,name=entity_query,json=entityQuery,proto3" json:"entity_query,omitempty"`
	// 按照sql查询（和实体查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 中声明
	// "id=1 and status in(3,4) and createtime >'2018' "
	SqlQuery string `protobuf:"bytes,2,opt,name=sql_query,json=sqlQuery,proto3" json:"sql_query,omitempty"`
	// 用空值当检索条件的字段
	QueryEmptyFields []string `protobuf:"bytes,3,rep,name=query_empty_fields,json=queryEmptyFields,proto3" json:"query_empty_fields,omitempty"`
	//排序条件 ["id":"desc","create_time":asc"]
	OrderBy map[string]string `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//是否查询主库，默认不读取 DB.READ
	Db DB `protobuf:"varint,5,opt,name=db,proto3,enum=wms_repository.DB" json:"db,omitempty"`
	//制定select查询的字段，如 "id,username,age"
	SelectField          string   `protobuf:"bytes,6,opt,name=select_field,json=selectField,proto3" json:"select_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{3}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetEntityQuery() *Repository {
	if m != nil {
		return m.EntityQuery
	}
	return nil
}

func (m *Query) GetSqlQuery() string {
	if m != nil {
		return m.SqlQuery
	}
	return ""
}

func (m *Query) GetQueryEmptyFields() []string {
	if m != nil {
		return m.QueryEmptyFields
	}
	return nil
}

func (m *Query) GetOrderBy() map[string]string {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *Query) GetDb() DB {
	if m != nil {
		return m.Db
	}
	return DB_READ
}

func (m *Query) GetSelectField() string {
	if m != nil {
		return m.SelectField
	}
	return ""
}

//分页查询
type PageQuery struct {
	//查询条件
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{4}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *PageQuery) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageQuery) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type EntityResult struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *Repository `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EntityResult) Reset()         { *m = EntityResult{} }
func (m *EntityResult) String() string { return proto.CompactTextString(m) }
func (*EntityResult) ProtoMessage()    {}
func (*EntityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{5}
}

func (m *EntityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityResult.Unmarshal(m, b)
}
func (m *EntityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityResult.Marshal(b, m, deterministic)
}
func (m *EntityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityResult.Merge(m, src)
}
func (m *EntityResult) XXX_Size() int {
	return xxx_messageInfo_EntityResult.Size(m)
}
func (m *EntityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityResult.DiscardUnknown(m)
}

var xxx_messageInfo_EntityResult proto.InternalMessageInfo

func (m *EntityResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EntityResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EntityResult) GetData() *Repository {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResult struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*Repository `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListResult) Reset()         { *m = ListResult{} }
func (m *ListResult) String() string { return proto.CompactTextString(m) }
func (*ListResult) ProtoMessage()    {}
func (*ListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{6}
}

func (m *ListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResult.Unmarshal(m, b)
}
func (m *ListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResult.Marshal(b, m, deterministic)
}
func (m *ListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResult.Merge(m, src)
}
func (m *ListResult) XXX_Size() int {
	return xxx_messageInfo_ListResult.Size(m)
}
func (m *ListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListResult proto.InternalMessageInfo

func (m *ListResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResult) GetData() []*Repository {
	if m != nil {
		return m.Data
	}
	return nil
}

type PageResult struct {
	Code                 int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *RepositoryPageData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PageResult) Reset()         { *m = PageResult{} }
func (m *PageResult) String() string { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()    {}
func (*PageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{7}
}

func (m *PageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResult.Unmarshal(m, b)
}
func (m *PageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResult.Marshal(b, m, deterministic)
}
func (m *PageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResult.Merge(m, src)
}
func (m *PageResult) XXX_Size() int {
	return xxx_messageInfo_PageResult.Size(m)
}
func (m *PageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResult.DiscardUnknown(m)
}

var xxx_messageInfo_PageResult proto.InternalMessageInfo

func (m *PageResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PageResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PageResult) GetData() *RepositoryPageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RepositoryPageData struct {
	CurrentPage          int32         `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Count                int32         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*Repository `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RepositoryPageData) Reset()         { *m = RepositoryPageData{} }
func (m *RepositoryPageData) String() string { return proto.CompactTextString(m) }
func (*RepositoryPageData) ProtoMessage()    {}
func (*RepositoryPageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b1f97d578d8366a, []int{8}
}

func (m *RepositoryPageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryPageData.Unmarshal(m, b)
}
func (m *RepositoryPageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryPageData.Marshal(b, m, deterministic)
}
func (m *RepositoryPageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryPageData.Merge(m, src)
}
func (m *RepositoryPageData) XXX_Size() int {
	return xxx_messageInfo_RepositoryPageData.Size(m)
}
func (m *RepositoryPageData) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryPageData.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryPageData proto.InternalMessageInfo

func (m *RepositoryPageData) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *RepositoryPageData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RepositoryPageData) GetList() []*Repository {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("wms_repository.DB", DB_name, DB_value)
	proto.RegisterType((*Repository)(nil), "wms_repository.Repository")
	proto.RegisterType((*Result)(nil), "wms_repository.Result")
	proto.RegisterType((*UpdateAndCondition)(nil), "wms_repository.UpdateAndCondition")
	proto.RegisterType((*Query)(nil), "wms_repository.Query")
	proto.RegisterMapType((map[string]string)(nil), "wms_repository.Query.OrderByEntry")
	proto.RegisterType((*PageQuery)(nil), "wms_repository.PageQuery")
	proto.RegisterType((*EntityResult)(nil), "wms_repository.EntityResult")
	proto.RegisterType((*ListResult)(nil), "wms_repository.ListResult")
	proto.RegisterType((*PageResult)(nil), "wms_repository.PageResult")
	proto.RegisterType((*RepositoryPageData)(nil), "wms_repository.RepositoryPageData")
}

func init() { proto.RegisterFile("repository_gen.proto", fileDescriptor_5b1f97d578d8366a) }

var fileDescriptor_5b1f97d578d8366a = []byte{
	// 801 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcb, 0x6e, 0xf3, 0x44,
	0x14, 0x4e, 0x9c, 0xab, 0x8f, 0x43, 0x48, 0x0f, 0xff, 0x5f, 0xdc, 0x50, 0x41, 0xf0, 0x86, 0x08,
	0x50, 0x16, 0x41, 0x42, 0xa8, 0x52, 0x17, 0xcd, 0xa5, 0x50, 0x09, 0x95, 0x62, 0x8a, 0x58, 0x5a,
	0x8e, 0x67, 0x88, 0x06, 0x7c, 0xab, 0x3d, 0x2e, 0xf2, 0x82, 0xc7, 0xe9, 0x13, 0xf1, 0x04, 0xbc,
	0x09, 0x9a, 0x19, 0x37, 0x76, 0x92, 0xa6, 0x17, 0x56, 0x99, 0x73, 0xbe, 0x6f, 0xbe, 0x73, 0xf5,
	0x28, 0xf0, 0x2e, 0xa1, 0x71, 0x94, 0x32, 0x1e, 0x25, 0xb9, 0xb3, 0xa6, 0xe1, 0x24, 0x4e, 0x22,
	0x1e, 0x61, 0xff, 0xaf, 0x20, 0x75, 0x4a, 0xc4, 0xfa, 0x57, 0x03, 0xb0, 0x37, 0x26, 0xf6, 0x41,
	0x63, 0xc4, 0xac, 0x8f, 0xea, 0xe3, 0x96, 0xad, 0x31, 0x82, 0x08, 0xcd, 0xd0, 0x0d, 0xa8, 0xa9,
	0x8d, 0xea, 0x63, 0xdd, 0x96, 0x67, 0xfc, 0x0c, 0x8c, 0x38, 0x89, 0xee, 0x59, 0xe8, 0x51, 0x87,
	0x11, 0xb3, 0x21, 0xc9, 0xf0, 0xe8, 0xba, 0x22, 0xf8, 0x31, 0x74, 0x3c, 0xc6, 0x73, 0x01, 0x36,
	0x25, 0xd8, 0x16, 0xe6, 0x15, 0x41, 0x13, 0x3a, 0x2e, 0x21, 0x09, 0x4d, 0x53, 0xb3, 0x25, 0x05,
	0x1f, 0x4d, 0x3c, 0x05, 0xdd, 0x8f, 0xc2, 0x35, 0xe3, 0x19, 0xa1, 0x66, 0x5b, 0x62, 0xa5, 0x03,
	0x87, 0xd0, 0xf5, 0x5d, 0xae, 0xc0, 0x8e, 0x04, 0x37, 0x36, 0x7e, 0x01, 0x1f, 0x56, 0x0a, 0xe5,
	0x79, 0x4c, 0xcd, 0xae, 0x0c, 0xda, 0x2f, 0xdd, 0xb7, 0x79, 0x4c, 0xf1, 0x18, 0xda, 0x29, 0x77,
	0x79, 0x96, 0x9a, 0xba, 0x4a, 0x4a, 0x59, 0xf8, 0x29, 0x40, 0xe0, 0xa6, 0x9c, 0x26, 0xb2, 0x50,
	0x90, 0xf2, 0x15, 0x8f, 0x28, 0x37, 0x8b, 0x89, 0xcb, 0xa9, 0xc3, 0x59, 0x40, 0x4d, 0x43, 0x11,
	0x94, 0xeb, 0x96, 0x29, 0x82, 0x97, 0xd0, 0x0d, 0xa1, 0xa7, 0x08, 0xca, 0x25, 0x08, 0xd6, 0x0c,
	0xda, 0x36, 0x4d, 0x33, 0x9f, 0x8b, 0x76, 0x7a, 0x11, 0xa1, 0x45, 0x83, 0xe5, 0x19, 0x07, 0xd0,
	0x08, 0xd2, 0x75, 0xd1, 0x61, 0x71, 0x14, 0x2c, 0xe2, 0x72, 0x57, 0x76, 0x56, 0xb7, 0xe5, 0xd9,
	0x7a, 0xa8, 0x03, 0xfe, 0x2a, 0x63, 0x5e, 0x84, 0x64, 0x1e, 0x85, 0x84, 0x71, 0x16, 0x85, 0x38,
	0x85, 0x36, 0x0d, 0x39, 0xe3, 0xb9, 0x94, 0x34, 0xa6, 0xc3, 0xc9, 0xf6, 0x7c, 0x27, 0xe5, 0x6c,
	0xed, 0x82, 0x89, 0x5f, 0x41, 0xeb, 0x2e, 0xa3, 0x49, 0x2e, 0x43, 0x1a, 0xd3, 0xf7, 0xbb, 0x57,
	0x7e, 0x16, 0xa0, 0xad, 0x38, 0x38, 0x81, 0x8f, 0x8a, 0xea, 0x69, 0x10, 0xf3, 0xdc, 0xf9, 0x9d,
	0x51, 0x9f, 0xa4, 0x66, 0x63, 0xd4, 0x18, 0xeb, 0xf6, 0x91, 0x82, 0x96, 0x02, 0xb9, 0x94, 0x80,
	0xf5, 0x8f, 0x06, 0x2d, 0x29, 0x80, 0xe7, 0xd0, 0x53, 0x01, 0x1d, 0x15, 0xed, 0xe5, 0x04, 0x0d,
	0xc5, 0x57, 0xd7, 0x3f, 0x01, 0x3d, 0xbd, 0xf3, 0x9d, 0x32, 0x53, 0xdd, 0xee, 0xa6, 0x77, 0xbe,
	0x02, 0xbf, 0x06, 0x94, 0xc0, 0x53, 0x49, 0x0d, 0x24, 0x52, 0xc9, 0x09, 0xcf, 0xa1, 0x1b, 0x25,
	0x84, 0x26, 0xce, 0x2a, 0x37, 0x9b, 0xa3, 0xc6, 0xd8, 0x98, 0x5a, 0x4f, 0xd6, 0x3c, 0xf9, 0x49,
	0xb0, 0x66, 0xf9, 0x32, 0xe4, 0x49, 0x6e, 0x77, 0x22, 0x65, 0xa1, 0x05, 0x1a, 0x59, 0xc9, 0x85,
	0xed, 0x4f, 0x71, 0xf7, 0xe2, 0x62, 0x66, 0x6b, 0x64, 0x85, 0x9f, 0x43, 0x2f, 0xa5, 0x3e, 0xf5,
	0xb8, 0xca, 0xa5, 0x58, 0x61, 0x43, 0xf9, 0x64, 0x1a, 0xc3, 0x33, 0xe8, 0x55, 0xf5, 0xc5, 0xdc,
	0xff, 0xa4, 0xaa, 0x2d, 0xba, 0x2d, 0x8e, 0xf8, 0x0e, 0x5a, 0xf7, 0xae, 0x9f, 0x3d, 0x7e, 0x6d,
	0xca, 0x38, 0xd3, 0xbe, 0xab, 0x5b, 0x6b, 0xd0, 0x6f, 0xdc, 0x35, 0x55, 0xc5, 0x6f, 0xe6, 0x57,
	0x7f, 0xc5, 0xfc, 0x10, 0x9a, 0xb1, 0xbb, 0x56, 0x92, 0x2d, 0x5b, 0x9e, 0xf1, 0x04, 0xba, 0xe2,
	0xd7, 0x09, 0xb3, 0xa0, 0xf8, 0x7a, 0x3b, 0xc2, 0xbe, 0xce, 0x02, 0x8b, 0x40, 0x6f, 0x29, 0x87,
	0xf0, 0xa6, 0x85, 0x9d, 0x54, 0x16, 0xf6, 0xf9, 0x11, 0xab, 0x65, 0x5e, 0x01, 0xfc, 0xc8, 0x52,
	0xfe, 0x3f, 0x63, 0x34, 0x5e, 0x15, 0xe3, 0x0f, 0x00, 0xd1, 0xb2, 0x37, 0xc5, 0xf8, 0x76, 0xab,
	0x0e, 0xeb, 0x70, 0x0c, 0xa1, 0xbc, 0x70, 0xb9, 0x5b, 0xc4, 0xfa, 0x1b, 0x70, 0x1f, 0x13, 0x3b,
	0xe1, 0x65, 0x49, 0x42, 0x43, 0xee, 0xc8, 0x11, 0xa8, 0xd8, 0x46, 0xe1, 0x13, 0x34, 0x31, 0x71,
	0x2f, 0xca, 0x42, 0x5e, 0x8c, 0x47, 0x19, 0xa2, 0x54, 0x9f, 0xa5, 0xfc, 0x35, 0xa5, 0x0a, 0xde,
	0x97, 0x27, 0xa0, 0x2d, 0x66, 0xd8, 0x85, 0xa6, 0xbd, 0xbc, 0x58, 0x0c, 0x6a, 0xa8, 0x43, 0xeb,
	0x37, 0xfb, 0xea, 0x76, 0x39, 0xa8, 0x4f, 0x1f, 0x9a, 0x70, 0x54, 0xf2, 0x7f, 0xa1, 0xc9, 0x3d,
	0xf3, 0x28, 0x5e, 0xc3, 0x60, 0x2e, 0x9f, 0xa7, 0xca, 0xcb, 0xff, 0x4c, 0x98, 0xe1, 0xe9, 0x2e,
	0x56, 0xdd, 0x11, 0xab, 0x86, 0x37, 0x30, 0x50, 0x6f, 0x53, 0x45, 0x6f, 0xaf, 0x7b, 0xfb, 0xaf,
	0xd7, 0xf0, 0x78, 0x3f, 0x66, 0xa1, 0x78, 0x09, 0x1f, 0x7c, 0x4f, 0x79, 0x45, 0xee, 0xe9, 0x2d,
	0x7f, 0x31, 0xb3, 0x1f, 0xe0, 0x68, 0x4b, 0x47, 0xac, 0xdd, 0x21, 0xad, 0xbd, 0x0e, 0x94, 0x3b,
	0x6a, 0xd5, 0x70, 0x0e, 0x83, 0x05, 0xf5, 0xe9, 0x56, 0x8d, 0x07, 0x84, 0x0e, 0x97, 0x75, 0x03,
	0xef, 0xb7, 0xd2, 0x11, 0x4b, 0x20, 0x53, 0x3a, 0xd9, 0xbd, 0xb2, 0xf9, 0xdc, 0xf7, 0xd3, 0x2a,
	0xd7, 0xda, 0xaa, 0xe1, 0x12, 0x70, 0x4b, 0x71, 0x2e, 0x37, 0xe8, 0xad, 0x89, 0xad, 0xda, 0xf2,
	0xdf, 0xc1, 0x37, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x41, 0x5a, 0xb5, 0xf9, 0x35, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryServiceClient is the client API for RepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryServiceClient interface {
	//创建
	CreateRepository(ctx context.Context, in *Repository, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明，如果要更新的是默认值 请使用update_empty_fields
	UpdateRepository(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepository(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepositoryList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	DeleteRepository(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepositoryPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepositoryCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
}

type repositoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryServiceClient(cc *grpc.ClientConn) RepositoryServiceClient {
	return &repositoryServiceClient{cc}
}

func (c *repositoryServiceClient) CreateRepository(ctx context.Context, in *Repository, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/CreateRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) UpdateRepository(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/UpdateRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetRepository(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/GetRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetRepositoryList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error) {
	out := new(ListResult)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/GetRepositoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) DeleteRepository(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/DeleteRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetRepositoryPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error) {
	out := new(PageResult)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/GetRepositoryPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetRepositoryCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wms_repository.RepositoryService/GetRepositoryCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServiceServer is the server API for RepositoryService service.
type RepositoryServiceServer interface {
	//创建
	CreateRepository(context.Context, *Repository) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明，如果要更新的是默认值 请使用update_empty_fields
	UpdateRepository(context.Context, *UpdateAndCondition) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepository(context.Context, *Query) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepositoryList(context.Context, *Query) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	DeleteRepository(context.Context, *Query) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepositoryPageList(context.Context, *PageQuery) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 中声明
	// 3.增加读写库查询判断
	GetRepositoryCount(context.Context, *Query) (*Result, error)
}

// UnimplementedRepositoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRepositoryServiceServer struct {
}

func (*UnimplementedRepositoryServiceServer) CreateRepository(ctx context.Context, req *Repository) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRepository not implemented")
}
func (*UnimplementedRepositoryServiceServer) UpdateRepository(ctx context.Context, req *UpdateAndCondition) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRepository not implemented")
}
func (*UnimplementedRepositoryServiceServer) GetRepository(ctx context.Context, req *Query) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepository not implemented")
}
func (*UnimplementedRepositoryServiceServer) GetRepositoryList(ctx context.Context, req *Query) (*ListResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositoryList not implemented")
}
func (*UnimplementedRepositoryServiceServer) DeleteRepository(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRepository not implemented")
}
func (*UnimplementedRepositoryServiceServer) GetRepositoryPageList(ctx context.Context, req *PageQuery) (*PageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositoryPageList not implemented")
}
func (*UnimplementedRepositoryServiceServer) GetRepositoryCount(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositoryCount not implemented")
}

func RegisterRepositoryServiceServer(s *grpc.Server, srv RepositoryServiceServer) {
	s.RegisterService(&_RepositoryService_serviceDesc, srv)
}

func _RepositoryService_CreateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repository)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).CreateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/CreateRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).CreateRepository(ctx, req.(*Repository))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_UpdateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCondition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).UpdateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/UpdateRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).UpdateRepository(ctx, req.(*UpdateAndCondition))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/GetRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetRepository(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetRepositoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetRepositoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/GetRepositoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetRepositoryList(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_DeleteRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).DeleteRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/DeleteRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).DeleteRepository(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetRepositoryPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetRepositoryPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/GetRepositoryPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetRepositoryPageList(ctx, req.(*PageQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetRepositoryCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetRepositoryCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wms_repository.RepositoryService/GetRepositoryCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetRepositoryCount(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _RepositoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wms_repository.RepositoryService",
	HandlerType: (*RepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRepository",
			Handler:    _RepositoryService_CreateRepository_Handler,
		},
		{
			MethodName: "UpdateRepository",
			Handler:    _RepositoryService_UpdateRepository_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _RepositoryService_GetRepository_Handler,
		},
		{
			MethodName: "GetRepositoryList",
			Handler:    _RepositoryService_GetRepositoryList_Handler,
		},
		{
			MethodName: "DeleteRepository",
			Handler:    _RepositoryService_DeleteRepository_Handler,
		},
		{
			MethodName: "GetRepositoryPageList",
			Handler:    _RepositoryService_GetRepositoryPageList_Handler,
		},
		{
			MethodName: "GetRepositoryCount",
			Handler:    _RepositoryService_GetRepositoryCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository_gen.proto",
}
